version: 2.1

parameters:
  service-name:
    type: string
    default: tls-client-forked

orbs:
  pinwheel-cicd: underdog-tech/pinwheel-cicd-orb@1.4
  macos: circleci/macos@2.4.0
  go: circleci/go@1.7.3

jobs:
  test:
    macos:
      xcode: 14.3.1
    working_directory: ~/<< pipeline.parameters.service-name >>
    executor:
      name: go/default
      tag: '1.20'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          race: true

workflows:
  test:
    jobs:
      - test:
          name: unit-test
          context: 'testing'
          filters:
            branches:
              ignore:
                - main
